### ISSUE TITLE
Homepage/FAQ How does jasper compare to OpenJPEG?

### ISSUE THREAD

**Issue by guettli** [jasper-software/jasper#111]
Please let us know: How does jasper compare to OpenJPEG?

Do you use the same source code base?

I would like to find this information (term "openjpeg") here: http://www.ece.uvic.ca/~frodo/jasper/

**Comment by xinyu391** [comment]
here is a benchmark of jpeg2000 codec:
http://www.fastcompression.com/products/jpeg2000/benchmarks-j2k.htm

**Comment by jubalh** [comment]
@MaxKellermann once you are through with your optimizations thiw would actually be interesting.

@mdadams maybe this can be added to your website indeed?
BTW we could also migrate to GitHub pages in case that makes it easier to update the website (it still shows 2.0.14 as latest release).

**Comment by mdadams** [comment]
Since there has not been any action on this item in a very long time and it does not correspond to a bug in the JasPer software or a request for a new feature in the software itself, I am closing this issue.
