### ISSUE TITLE
Out of bound read in jpc_bitstream_align

### ISSUE THREAD

**Issue by adarshdinesh** [jasper-software/jasper#125]
gdb-peda$ r out_of_bound_read_jpc_bitstream_align
Starting program: /home/sandbox/Desktop/fuzz/bin out_of_bound_read_jpc_bitstream_align
warning: trailing garbage in marker segment (40 bytes)
warning: not enough tile data (11 bytes)
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: corrupt code stream
warning: bad segmentation symbol
warning: corrupt code stream
warning: corrupt code stream
warning: corrupt code stream
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad termination pattern detected
warning: bad termination pattern detected
warning: bad segmentation symbol
warning: bad termination pattern detected
warning: bad segmentation symbol
warning: bad termination pattern detected
warning: bad segmentation symbol
warning: bad termination pattern detected
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad segmentation symbol
warning: bad termination pattern detected

Program received signal SIGSEGV, Segmentation fault.

 [----------------------------------registers-----------------------------------]
RAX: 0x50000 
RBX: 0x0 
RCX: 0x607e00 --> 0x4000 ('')
RDX: 0x812430 --> 0x340 
RSI: 0x7ffff784fb48 --> 0x643930 --> 0x0 
RDI: 0x50000 
RBP: 0x7fffffffdc60 --> 0x7fffffffdc90 --> 0x7fffffffdd00 --> 0x7fffffffdd40 --> 0x7fffffffdd80 --> 0x7fffffffddc0 (--> ...)
RSP: 0x7fffffffdc40 --> 0x7fffffffdc70 --> 0x7fffffffdc90 --> 0x7fffffffdd00 --> 0x7fffffffdd40 --> 0x7fffffffdd80 (--> ...)
RIP: 0x7ffff7b84560 (<jpc_bitstream_align+16>:	mov    eax,DWORD PTR [rax+0x20])
R8 : 0x643940 --> 0x812430 --> 0x340 
R9 : 0x0 
R10: 0x72 ('r')
R11: 0x7ffff7bb3e54 (<jpc_tagtree_destroy>:	push   rbp)
R12: 0x400d80 (<_start>:	xor    ebp,ebp)
R13: 0x7fffffffdf40 --> 0x2 
R14: 0x0 
R15: 0x0
EFLAGS: 0x10202 (carry parity adjust zero sign trap INTERRUPT direction overflow)
[-------------------------------------code-------------------------------------]
   0x7ffff7b84554 <jpc_bitstream_align+4>:	sub    rsp,0x20
   0x7ffff7b84558 <jpc_bitstream_align+8>:	mov    QWORD PTR [rbp-0x18],rdi
   0x7ffff7b8455c <jpc_bitstream_align+12>:	mov    rax,QWORD PTR [rbp-0x18]
=> 0x7ffff7b84560 <jpc_bitstream_align+16>:	mov    eax,DWORD PTR [rax+0x20]
   0x7ffff7b84563 <jpc_bitstream_align+19>:	and    eax,0x1
   0x7ffff7b84566 <jpc_bitstream_align+22>:	test   eax,eax
   0x7ffff7b84568 <jpc_bitstream_align+24>:	je     0x7ffff7b84585 <jpc_bitstream_align+53>
   0x7ffff7b8456a <jpc_bitstream_align+26>:	mov    rax,QWORD PTR [rbp-0x18]
[------------------------------------stack-------------------------------------]
0000| 0x7fffffffdc40 --> 0x7fffffffdc70 --> 0x7fffffffdc90 --> 0x7fffffffdd00 --> 0x7fffffffdd40 --> 0x7fffffffdd80 (--> ...)
0008| 0x7fffffffdc48 --> 0x50000 
0016| 0x7fffffffdc50 --> 0x7fffffffdf40 --> 0x2 
0024| 0x7fffffffdc58 --> 0x7ffff7b77416 (<jas_free+58>:	nop)
0032| 0x7fffffffdc60 --> 0x7fffffffdc90 --> 0x7fffffffdd00 --> 0x7fffffffdd40 --> 0x7fffffffdd80 --> 0x7fffffffddc0 (--> ...)
0040| 0x7fffffffdc68 --> 0x7ffff7b83ae6 (<jpc_bitstream_close+31>:	test   eax,eax)
0048| 0x7fffffffdc70 --> 0x7fffffffdc90 --> 0x7fffffffdd00 --> 0x7fffffffdd40 --> 0x7fffffffdd80 --> 0x7fffffffddc0 (--> ...)
0056| 0x7fffffffdc78 --> 0x50000 
[------------------------------------------------------------------------------]
Legend: code, data, rodata, value
Stopped reason: SIGSEGV
0x00007ffff7b84560 in jpc_bitstream_align () from /usr/lib/libjasper.so.4

gdb-peda$ backtrace 
#0  0x00007ffff7b84560 in jpc_bitstream_align () from /usr/lib/libjasper.so.4
#1  0x00007ffff7b83ae6 in jpc_bitstream_close () from /usr/lib/libjasper.so.4
#2  0x00007ffff7b8b36b in jpc_dec_tilefini () from /usr/lib/libjasper.so.4
#3  0x00007ffff7b89cd2 in jpc_dec_process_sod () from /usr/lib/libjasper.so.4
#4  0x00007ffff7b89425 in jpc_dec_decode () from /usr/lib/libjasper.so.4
#5  0x00007ffff7b89005 in jpc_decode () from /usr/lib/libjasper.so.4
#6  0x00007ffff7b731cd in jas_image_decode () from /usr/lib/libjasper.so.4
#7  0x0000000000400f4f in main ()
#8  0x00007ffff74ac830 in __libc_start_main (main=0x400e76 <main>, argc=0x2, argv=0x7fffffffdf48, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdf38) at ../csu/libc-start.c:291
#9  0x0000000000400da9 in _start ()
gdb-peda$ 

[out_of_bound_read_jpc_bitstream_align.zip](https://github.com/mdadams/jasper/files/870056/out_of_bound_read_jpc_bitstream_align.zip)

**Comment by asarubbo** [comment]
with your testcase asan gives me the same stacktrace as reported in #90 
I'd say that it is a duplicate.

**Comment by adarshdinesh** [comment]
From my limited idea, ASAN stops when it finds some heap related issues. Here the root cause looks different from #90

gdb-peda$ backtrace 
#0  0x0000000000453947 in jpc_bitstream_align (bitstream=0x50000) at /home/sandbox/jasper/src/libjasper/jpc/jpc_bs.c:336
#1  0x0000000000452f05 in jpc_bitstream_close (bitstream=0x50000) at /home/sandbox/jasper/src/libjasper/jpc/jpc_bs.c:131
#2  0x000000000041af63 in jpc_dec_tilefini (dec=0x675580, tile=0x675f18) at /home/sandbox/jasper/src/libjasper/jpc/jpc_dec.c:1004
#3  0x00000000004198dc in jpc_dec_process_sod (dec=0x675580, ms=0x0) at /home/sandbox/jasper/src/libjasper/jpc/jpc_dec.c:661
#4  0x0000000000419042 in jpc_dec_decode (dec=0x675580) at /home/sandbox/jasper/src/libjasper/jpc/jpc_dec.c:425
#5  0x0000000000418c35 in jpc_decode (in=0x673450, optstr=0x0) at /home/sandbox/jasper/src/libjasper/jpc/jpc_dec.c:262
#6  0x0000000000406cb3 in jas_image_decode (in=0x673450, fmt=0x5, optstr=0x0) at /home/sandbox/jasper/src/libjasper/base/jas_image.c:444
#7  0x0000000000405ed0 in main (argc=0x2, argv=0x7fffffffdf78) at /home/sandbox/jasper/src/appl/imgcmp.c:146
#8  0x00007ffff7725830 in __libc_start_main (main=0x405df6 <main>, argc=0x2, argv=0x7fffffffdf78, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdf68) at ../csu/libc-start.c:291
#9  0x0000000000405d29 in _start ()

**Comment by jubalh** [comment]
Fixed with our merges from jasper-maint:

```
imginfo -f ~/jasper/out_of_bound_read_jpc_bitstream_align
image too large
cannot load image
```

Not entirely sure which commit, and don't think git bisecting it is worth it here.
2.0.19 is thus fixed.
