### ISSUE TITLE
Incorrect jp2_boxinfolookup() return value check in jp2_box_create()

### ISSUE THREAD

**Issue by thoger** [jasper-software/jasper#129]
`jp2_box_create()` contains this code:

~~~
	if (!(boxinfo = jp2_boxinfolookup(type))) {
		return 0;
	}
~~~

However, `jp2_boxinfolookup()` does not return NULL.  It either returns pointer to one of the `jp2_boxinfos[]` member, or to `jp2_boxinfo_unk`.  Maybe some older versions used to return NULL.

Note that if `jp2_boxinfolookup()` could return NULL, there would be memory leak problem in `jp2_box_create()` - `box` allocated in `jp2_box_create0()` would not be freed in case of lookup error.

Note that `assert(boxinfo)` after `jp2_boxinfolookup()` in `jp2_box_dump()` is redundant for the same reason.

**Comment by jubalh** [comment]
@thoger can you prepare a PR?

**Comment by MaxKellermann** [comment]
Fix for both problems is part of https://github.com/jasper-software/jasper/pull/229
