### ISSUE TITLE
null pointer deference in jas_malloc.c

### ISSUE THREAD

**Issue by bestshow** [jasper-software/jasper#131]
on 2.0.12

#imginfo -f $FILE
=================================================================
BUS on unknown address 0x000000000000 (pc 0x00000041fdef bp 0xbebebebebebebeae sp 0x7ffdc1524f30 T0)
    #0 0x41fdee in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t> /home/haojun/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:81
    #1 0x41fdee in __asan::Allocator::AtomicallySetQuarantineFlagIfAllocated(__asan::AsanChunk*, void*, __sanitizer::BufferedStackTrace*) /home/haojun/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:506
    #2 0x41fdee in __asan::Allocator::Deallocate(void*, unsigned long, __sanitizer::BufferedStackTrace*, __asan::AllocType) /home/haojun/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:570
    #3 0x41fdee in __asan::asan_free(void*, __sanitizer::BufferedStackTrace*, __asan::AllocType) /home/haojun/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_allocator.cc:783
    #4 0x4dfa0c in free /home/haojun/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/asan_malloc_linux.cc:50
    #5 0x7f9f55a8ff31 in jas_free /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/libjasper/base/jas_malloc.c:259:2
    #6 0x7f9f55aaf096 in jp2_cdef_destroy /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/libjasper/jp2/jp2_cod.c:230:3
    #7 0x7f9f55aaf9b8 in jp2_box_destroy /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/libjasper/jp2/jp2_cod.c:212:3
    #8 0x7f9f55ab0398 in jp2_box_get /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/libjasper/jp2/jp2_cod.c:319:3
    #9 0x7f9f55ab4ab5 in jp2_decode /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/libjasper/jp2/jp2_dec.c:159:16
    #10 0x7f9f55a821d7 in jas_image_decode /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/libjasper/base/jas_image.c:444:16
    #11 0x515ee5 in main /home/haojun/Downloads/testopensourcecode/jasper-2.0.12/src/appl/imginfo.c:238:16
    #12 0x7f9f54b59b34 in __libc_start_main (/lib64/libc.so.6+0x21b34)
    #13 0x41ae8b in _start (/home/haojun/Downloads/testopensourcecode/jasper-2.0.12_build/src/appl/imginfo+0x41ae8b)

BUS /home/haojun/Downloads/llvm-clang/llvm/projects/compiler-rt/lib/asan/../sanitizer_common/sanitizer_atomic_clang.h:81 in atomic_compare_exchange_strong<__sanitizer::atomic_uint8_t>
==15347==ABORTING
testcase:
https://github.com/bestshow/p0cs/blob/master/1010-nullptr-jas_malloc

**Comment by thoger** [comment]
This seems to be the same problem as #112, which was corrected in e96fc4f.
