### ISSUE TITLE
Strange abort() statements

### ISSUE THREAD

**Issue by hwiesmann** [jasper-software/jasper#141]
In a couple of files you will find something like
`
    return 0;
    abort();

error:
`
The abort() function is useless as it is never reached.

**Comment by jubalh** [comment]
Can you be a bit more specific and mention the files/lines?

**Comment by MaxKellermann** [comment]
I believe all of those unreachable `abort()` calls were fixed in the past 3 years, because I did not find any. Reopen if you believe there are still problems.
