### ISSUE TITLE
jasper crashes -- assertion failure

### ISSUE THREAD

**Issue by thuanpv** [jasper-software/jasper#174]
Hi all,

This bug was found with AFLSmart, an extension of AFL. Thanks also to Marcel Böhme, Andrew Santosa and Alexandru Razvan Caciulescu. 

This bug was found on Ubuntu 16.04 64-bit.

To reproduce:
`imginfo -f jasper_crash1.jpg
`
Error message:
```
warning: trailing garbage in marker segment (214 bytes)
imginfo: /home/ubuntu/experiments/jasper/src/libjasper/jpc/jpc_dec.c:1296: jpc_dec_process_siz: Assertion `dec->numhtiles >= 0' failed.
Aborted
```

Valgrind says:
```
==34446== Process terminating with default action of signal 6 (SIGABRT)
==34446==    at 0x5236428: raise (raise.c:54)
==34446==    by 0x5238029: abort (abort.c:89)
==34446==    by 0x522EBD6: __assert_fail_base (assert.c:92)
==34446==    by 0x522EC81: __assert_fail (assert.c:101)
==34446==    by 0x4F118B6: jpc_dec_process_siz (jpc_dec.c:1296)
==34446==    by 0x4F1C1D8: jpc_dec_decode (jpc_dec.c:424)
==34446==    by 0x4F1C1D8: jpc_decode (jpc_dec.c:261)
==34446==    by 0x4EA8E03: jas_image_decode (jas_image.c:442)
==34446==    by 0x4018D5: main (imginfo.c:238)
```
Regards,
Thuan

![jasper_crash1](https://user-images.githubusercontent.com/3669460/39092310-6c83def8-4635-11e8-9a1f-942c15571b15.jpg)

**Comment by thoger** [comment]
The same assertion and traceback as in #165 - probably a duplicate.

**Comment by MaxKellermann** [comment]
This vulnerability has been fixed in our fork: https://github.com/jasper-maint/jasper/
