### ISSUE TITLE
jasper crashes -- SIGABRT

### ISSUE THREAD

**Issue by thuanpv** [jasper-software/jasper#175]
Hi all,

This bug was found with AFLSmart, an extension of AFL. Thanks also to Marcel Böhme, Andrew Santosa and Alexandru Razvan Caciulescu.

This bug was found on Ubuntu 16.04 64-bit.

To reproduce:
`imginfo -f jasper_crash2.jpg
`
Error message:

```
warning: trailing garbage in marker segment (5 bytes)
warning: trailing garbage in marker segment (2 bytes)
Aborted
```

Valgrind says:

```
warning: trailing garbage in marker segment (5 bytes)
warning: trailing garbage in marker segment (2 bytes)
==34503== 
==34503== Process terminating with default action of signal 6 (SIGABRT)
==34503==    at 0x5236428: raise (raise.c:54)
==34503==    by 0x5238029: abort (abort.c:89)
==34503==    by 0x4F25B88: jpc_dec_process_sot (jpc_dec.c:488)
==34503==    by 0x4F1C1D8: jpc_dec_decode (jpc_dec.c:424)
==34503==    by 0x4F1C1D8: jpc_decode (jpc_dec.c:261)
==34503==    by 0x4EA8E03: jas_image_decode (jas_image.c:442)
==34503==    by 0x4018D5: main (imginfo.c:238)
==34503== 
```
Regards,

Thuan

![jasper_crash2](https://user-images.githubusercontent.com/3669460/39092327-c15a9d68-4635-11e8-8b4c-35db5a212ed2.jpg)

**Comment by thoger** [comment]
The same abort and traceback as in #166 - probably a duplicate.
