### ISSUE TITLE
jiv fails assertion

### ISSUE THREAD

**Issue by themaddoctor** [jasper-software/jasper#177]
jiv: /username/gtk-chain/jasper-2.0.12/src/appl/jiv.c:384: displayfunc: Assertion `JAS_ABS(((double) regheight / regwidth) - ((double) gs.viewportheight / gs.viewportwidth)) < 1e-5' failed.
Aborted

On linux 64-bit, jasper 2.0.14, libjpegturbo 1.5.3. All built from source.

Jiv fails for some images, but not all. Here is one that causes the failure:

![test-square-jiv-fails](https://user-images.githubusercontent.com/6364418/41323215-2b9f0d68-6e7b-11e8-8d22-ee3c29a0b06a.jpg)

**Comment by themaddoctor** [comment]
If I run jasper on the file, and create a jp2 file, it also causes jiv to fail.

**Comment by themaddoctor** [comment]
Failure does not occur with the jiv from jasper-1.900

**Comment by MaxKellermann** [comment]
dc129830baf8cfe104454d3a6e426f55af51b1d3 is the first bad commit
