### ISSUE TITLE
Tests will fail on bash version 4.0 to 4.1

### ISSUE THREAD

**Issue by hisakatha** [jasper-software/jasper#179]
[test/bin/utilities](https://github.com/mdadams/jasper/blob/master/test/bin/utilities) includes `-g` option of `declare` command of `bash`, [which was introduced to bash 4.2.](http://git.savannah.gnu.org/cgit/bash.git/tree/NEWS?id=a0c0a00fc419b7bc08202a79134fcd5bc0427071#n428) Moreover, `test/bin/run_test_3` will be skipped when the version of bash is less than 4.0. Therefore, the test will fail if the version of bash is between 4.0 and 4.1.
Actually, in my environment (CentOS6), the version of bash is 4.1.2 and the test failed.
Could you fix this problem, please?

**Comment by mdadams** [comment]
It is my understanding that Bash is already up to version 4.4 and 5.0 is in alpha release.  So, 4.0 to 4.1 is quite old.  My suggestions would be to upgrade Bash.  This said, the script should check to ensure that the version of Bash is recent enough.  I think that it currently just checks for 4.0.  I guess it should check for 4.2 or greater?

**Comment by hisakatha** [comment]
I think the test scripts are run using a system bash (`/bin/bash`). So, to upgrade the system bash, I have to ask my system administrator to do so. It may be difficult for fear of lack of compatibility, so I would appreciate if the tests checked for bash 4.2 or greater (or, ideally, the tests were implemented without `-g` option).

**Comment by jubalh** [comment]
> The problem is that the -g option is needed. So, the best solution would be to disable the test script altogether if the version of Bash is too old.

Agreed
