### ISSUE TITLE
Generate libtool files for static builds

### ISSUE THREAD

**Issue by fiorix** [jasper-software/jasper#186]
Building jasper-2.0.14 static, and looking at the lib64 directory there's libjasper.a but no libjasper.la. The result is that projects such as GraphicsMagick which depend on libjasper and use libtool cannot statically link to libjasper due to the lack of libtool's .la file.

I'm no cmake expert but found https://gitlab.kitware.com/cmake/community/wikis/contrib/macros/LibtoolFile and tried to add the .cmake file with the macro definition in build/cmake/modules then call the macro in src/libjasper/CMakeLists.txt but it doesn't work, complains the macro CREATE_LIBTOOL_FILE doesn't exist.

I'd really appreciate if this could be added and I'm willing to help testing.

**Comment by MaxKellermann** [comment]
What exactly is the problem?
You wrote "cannot statically link to libjasper due to the lack of libtool's .la file", but that is very unspecific. It does not describe any problem.
Btw. your PR https://github.com/jasper-software/jasper/pull/187 was closed for the wrong reasons (IMHO).

**Comment by mdadams** [comment]
Since several months have passed without a response to Max's request for more information (so that the problem can be better understood), I am closing this issue.
