### ISSUE TITLE
Problems with version 1.900.1 and 2.0.14

### ISSUE THREAD

**Issue by avzuquete** [jasper-software/jasper#212]
JasPer is distributed as a Linux package, but only 1.900.1.
It cannot properly handle some JPEG-2000 images, jp2_decode returns a null pointer without any error, which is odd. Check attached JPEG-2000 file within ZIP file.

JasPer 2.0.14 has no Linux package. When attempting to build it from the source, it gives an error related with an installation ARCHIVE. Upon removing the instalation options, it generates Makefiles but with wrong configuration options (relatively to include files, such as fctnl.h, unistd.h, etc.).

[revogado.zip](https://github.com/mdadams/jasper/files/3905853/revogado.zip)

**Comment by MaxKellermann** [comment]
I cannot reproduce either problem. I suppose it is long gone.
If you still see problems, write a new bug report on the latest JasPer release. And please always create separate bug reports for separate problems.
