### ISSUE TITLE
Compression size issue

### ISSUE THREAD

**Issue by zihaoliu123** [jasper-software/jasper#213]
Hi, 

Recently, I compared the compression rate of jasper by using -qtable and -quality option with all other settings the same. 
When I set the values in my quantization table file exactly the same as the default value in JPEG quantization table and compare it with -quality=75, the compression rates are totally different. 
Using -qtable option has a much smaller bit rate compared with using -quality option, (i.e. 30kb v.s. 50kb). 
Any kind of help would be much appreciated. Looking forward to your kind reply.

**Comment by MaxKellermann** [comment]
I don't understand any of what you wrote. Please rephrase and describe what kind of reply you desire.

**Comment by mdadams** [comment]
Since almost a year has passed without the user providing the clarification that Max requested, I am closing this issue.
