### ISSUE TITLE
Unable to build without OpenGL library

### ISSUE THREAD

**Issue by dmilith** [jasper-software/jasper#219]
I'm trying to build jasper with only jpeg library with `-DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF -DJAS_ENABLE_OPENGL=OFF -DJAS_ENABLE_PROGRAMS=OFF -DJAS_ENABLE_DOC=OFF` options, but configuration phase crashes:

```
JAS_ENABLE_OPENGL: OFF
JAS_HAVE_OPENGL: 0
CMake Error: File /Software/Jasper/.src_7f1d248e238830ba/jasper-version-2.0.17/build/jasper.pc.in does not exist.
CMake Error at CMakeLists.txt:411 (configure_file):
  configure_file Problem configuring file
```

What's the point of having options that can't be turned off?

**Comment by MaxKellermann** [comment]
There's something wrong with your JasPer sources. The file `jasper.pc.in` exists in the JasPer source distribution, but does not appear to exist on your hard disk. Find out why.
I say this is not a JasPer bug, but a problem local to your computer.

> What's the point of having options that can't be turned off?

That's not a clever question, because it asserts that it can't be turned off - but it can be turned off. This leads to a problem, but this doesn't mean it can't be turned off.

**Comment by dmilith** [comment]
I took tar.gz from site… and once from latest tarball from github.

**Comment by dmilith** [comment]
Maybe it's cause I try doing build from build/ directory not /?

**Comment by MaxKellermann** [comment]
I don't understand. Be more specific and exact.

**Comment by dmilith** [comment]
By default all cmake builds are executed from build/ directory in source root. Can you share your build process please?

**Comment by dmilith** [comment]
What's even more weird is that build/jasper.pc.in exists in source directory. I'm using cmake 3.16.0

**Comment by MaxKellermann** [comment]
> By default all cmake builds are executed from build/ directory in source root.

I have never heard of that. Where can I read documentation about it?

> What's even more weird is that build/jasper.pc.in exists in source directory.

That's not weird. That's how it's supposed to be, and that's what I said in my first reply.

**Comment by dmilith** [comment]
So jasper.pc.in exists in that exact path but cmake tells it's not.

**Comment by MaxKellermann** [comment]
You didn't answer my question.
You claimed this happens when disabling OpenGL, but I think that's not true.

> So jasper.pc.in exists in that exact path but cmake tells it's not.

Then you should consult cmake support.

**Comment by dmilith** [comment]
Don't worry, will not report anything else to you ;)
