### ISSUE TITLE
"incorrect packet sequence number" after merging "Fix SOP marker checking"

### ISSUE THREAD

**Issue by MaxKellermann** [jasper-software/jasper#233]
After merging https://github.com/jasper-software/jasper/pull/232 the file https://github.com/bitsgalore/jp2kMagic/blob/master/sampleImages/balloon.jp2?raw=true does not load anymore:
```
incorrect packet sequence number 0 was found, but expected 486
jpc_dec_decodepkts failed
error: cannot decode code stream
cannot load image
```
@osamu620, is this a broken file? Should we support broken files like that? The whole point of https://github.com/jasper-software/jasper/pull/232 was to detect and reject such files.

**Comment by osamu620** [comment]
> @osamu620, is this a broken file? Should we support broken files like that? The whole point of #232 was to detect and reject such files.

I'm sorry this is a bug due to my mistake. The codestream included in the JP2 file which you put as a link seems to be correct. I have made a PR #234 to eliminate this bug.
