### ISSUE TITLE
Floating Invalid in libjasper/jpc/jpc_enc.c

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [jasper-software/jasper#260]
When compiled with the Intel compilers (version 18.0.3 20180410, JasPer version 2.0.22), the ternary operation at lines [1393-1395](https://github.com/jasper-software/jasper/blob/9a2835a81ce9c41a48f36dadce79f110da8d6c75/src/libjasper/jpc/jpc_enc.c#L1393-L1395) returns a floating invalid when `cp->totalsize == UINT_FAST32_MAX`.  Replacing the ternary operation with the if-else block located on lines [1397-1401](https://github.com/jasper-software/jasper/blob/9a2835a81ce9c41a48f36dadce79f110da8d6c75/src/libjasper/jpc/jpc_enc.c#L1397-L1401) returns the expected value of `UINT_FAST32_MAX`.

**Comment by jubalh** [comment]
What's the compiler define macro for that intel compilers?
On the other hand I don't get why we wouldn't want the more readable expression on the latter lines in all cases. I'll create a PR for this and let @mdadams review it.

**Comment by mdadams** [comment]
@jubalh Removing the ternary operator seems like a reasonable solution to me.
