### ISSUE TITLE
oss-fuzz 31275 graphicsmagick:coder_PGX_fuzzer: Undefined-shift in pgx_getword

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#270]
oss-fuzz 31275 is determined to be a JasPer issue.  The full issue content is included in the attached tarball.  Please fix!
[oss-fuzz-31275.tar.gz](https://github.com/jasper-software/jasper/files/6135023/oss-fuzz-31275.tar.gz)

**Comment by mdadams** [comment]
This overflow is benign, currently.  Since it occurs in a utility function where it is probably better to be careful about overflow (for the sake of future code changes), and there is no performance impact, I have fixed this issue (on the master branch).
