### ISSUE TITLE
oss-fuzz 31281 graphicsmagick:coder_J2C_fuzzer: Out-of-memory in coder_J2C_fuzzer

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#271]
oss-fuzz 31281 is determined to be a JasPer issue.  The full issue content is included in the attached tarball.  Please fix!

[oss-fuzz-31281.tar.gz](https://github.com/jasper-software/jasper/files/6135026/oss-fuzz-31281.tar.gz)

**Comment by mdadams** [comment]
Duplicate of #274.  Fixed on master branch.
