### ISSUE TITLE
oss-fuzz 31290 graphicsmagick:coder_JPC_fuzzer: Out-of-memory in coder_JPC_fuzzer

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#272]
oss-fuzz 31290 is determined to be a JasPer issue.  The full issue content is included in the attached tarball.  Please fix!

[oss-fuzz-31290.tar.gz](https://github.com/jasper-software/jasper/files/6135030/oss-fuzz-31290.tar.gz)

**Comment by mdadams** [comment]
Yet another duplicate of #274. :(
