### ISSUE TITLE
oss-fuzz 31300 graphicsmagick:coder_JP2_fuzzer: Out-of-memory in coder_JP2_fuzzer

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#273]
oss-fuzz 31300 is determined to be a JasPer issue.  The full issue content is included in the attached tarball.  Please fix!

[oss-fuzz-31300.tar.gz](https://github.com/jasper-software/jasper/files/6135034/oss-fuzz-31300.tar.gz)

**Comment by mdadams** [comment]
Yet another duplicate of #274. :(
