### ISSUE TITLE
oss-fuzz 31310 graphicsmagick:coder_PGX_fuzzer: Out-of-memory in coder_PGX_fuzzer

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#274]
oss-fuzz 31310 is determined to be a JasPer issue.  The full issue content is included in the attached tarball.  Please fix!

[oss-fuzz-31310.tar.gz](https://github.com/jasper-software/jasper/files/6135038/oss-fuzz-31310.tar.gz)

**Comment by mdadams** [comment]
Fixed on master.
