### ISSUE TITLE
oss-fuzz 31524 graphicsmagick:enhance_fuzzer: Out-of-memory in enhance_fuzzer

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#275]
oss-fuzz 31524 is determined to be a JasPer issue.  The full issue content is included in the attached tarball.  Please fix!

In this case, JasPer appears to be successful, but the returned image size is not rational.

[oss-fuzz-31524.tar.gz](https://github.com/jasper-software/jasper/files/6135042/oss-fuzz-31524.tar.gz)

**Comment by mdadams** [comment]
Another duplicate of #274.  (Already fixed on master branch.)
