### ISSUE TITLE
oss-fuzz 31842 graphicsmagick:coder_JPC_fuzzer: Undefined-shift in jp2_getint

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#278]
oss-fuzz 31842 is determined to be a JasPer issue.  The full issue content is included in the attached tarball.  Please fix!

[oss-fuzz-31842.tar.gz](https://github.com/jasper-software/jasper/files/6135056/oss-fuzz-31842.tar.gz)

**Comment by mdadams** [comment]
I looked at this problem in more detail.  In the given test case, JasPer should have stopped decoding before the bad shifts occurred.  I have fixed this problem now on the master branch.
