### ISSUE TITLE
oss-fuzz 31865 graphicsmagick:coder_J2C_fuzzer: Undefined-shift in inttobits

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#279]
oss-fuzz 31865 is determined to be a JasPer issue.  The full issue content is included in the attached tarball.  Please fix!

[oss-fuzz-31865.tar.gz](https://github.com/jasper-software/jasper/files/6135059/oss-fuzz-31865.tar.gz)

**Comment by mdadams** [comment]
This is a benign overflow issue.  Again, in the interest of performance, overflow of sample data is allowed to occur during encoding/decoding.  Overflow of sample data just adds distortion to the decoded image.  It will not cause any security vulnerabilities.
