### ISSUE TITLE
oss-fuzz 31967 graphicsmagick:coder_WPG_fuzzer: Out-of-memory in coder_WPG_fuzzer

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#281]
oss-fuzz 31967 is determined to be a JasPer issue.  The full issue content is included in the attached tarball.  Please fix!

While the input file that oss-fuzz tested with is a WPG file, the embedded PGX content from the WPG is extracted as wpg-blob.PGX, and that is the file which should be tested with.

[oss-fuzz-31967.tar.gz](https://github.com/jasper-software/jasper/files/6135064/oss-fuzz-31967.tar.gz)

**Comment by mdadams** [comment]
This also appears to be duplicate of #274.
