### ISSUE TITLE
Problem with 2.0.28

### ISSUE THREAD

**Issue by hirokeynu** [jasper-software/jasper#289]
When I open [file9.jp2](https://gwg.nga.mil/ntb/baseline/software/testfile/Jpeg2000/jpeg2k.htm) , an error occurred at 
https://github.com/jasper-software/jasper/blob/5173ef1fbcdd90533a4450f51600ad42b14cd773/src/libjasper/jp2/jp2_dec.c#L372.

Is this file still supported?

It looks like dec-> cdef isn't needed in this block. So I commented out check of null pointer and line:379 , line:417.

Then an error occurred at https://github.com/jasper-software/jasper/blob/5173ef1fbcdd90533a4450f51600ad42b14cd773/src/libjasper/jp2/jp2_dec.c#L428.

Is this part necessary even after the following modifications?
・https://github.com/jasper-software/jasper/issues/268 
・https://github.com/jasper-software/jasper/issues/269

**Comment by mdadams** [comment]
@hirokeynu  Previously, the code for the JP2 decoder was too lax in its checking of the input codestream.  In fixing this problem, it appears that the code was made overly restrictive, rejecting valid codestreams, as you have observed.  As best I can tell, your analysis is correct.  I have removed some of the checks that appear unnecessary, and this still appears to reject the invalid codestreams for #268 and #269.  Now, however, it does accept the valid codestream that you mentioned.  So your problem should be fixed now in d1845f5e4abe45e1cfb420e3222686c2eae8071b.
