### ISSUE TITLE
jasper crashes due to an assertion failure

### ISSUE THREAD

**Issue by thuanpv** [jasper-software/jasper#291]
Hi all,

This bug was found with AFLTeam, a new extension of AFL, on Ubuntu 18.04 64 bit -- revision 543e18d (HEAD)

**To reproduce (using the attached crash-triggering file -- please unzip first because GitHub does not support jp2 file)**
jasper -f jasper_crash_1.jp2 -t jp2 -T bmp -F /dev/null

**Error message:**
jasper: src/libjasper/base/jas_icc.c:1021: int jas_iccxyz_input(jas_iccattrval_t *, jas_stream_t *, unsigned int): Assertion `len == 4 * 3' failed.

**Call stack generated by GDB:**
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff73b6921 in __GI_abort () at abort.c:79
#2  0x00007ffff73a648a in __assert_fail_base (fmt=0x7ffff752d750 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x7ffff7baeeb6 "len == 4 * 3", 
    file=file@entry=0x7ffff7baec60 "src/libjasper/base/jas_icc.c", line=line@entry=1021, 
    function=function@entry=0x7ffff7baeec3 "int jas_iccxyz_input(jas_iccattrval_t *, jas_stream_t *, unsigned int)") at assert.c:92
#3  0x00007ffff73a6502 in __GI___assert_fail (assertion=0x7ffff7baeeb6 "len == 4 * 3", file=0x7ffff7baec60 "src/libjasper/base/jas_icc.c", 
    line=1021, function=0x7ffff7baeec3 "int jas_iccxyz_input(jas_iccattrval_t *, jas_stream_t *, unsigned int)") at assert.c:101
#4  0x00007ffff7b1f5de in jas_iccxyz_input (attrval=0x63c9e0, in=0x66a5f0, len=62476) at src/libjasper/base/jas_icc.c:1021
#5  0x00007ffff7b19c96 in jas_iccprof_load (in=<optimised out>) at src/libjasper/base/jas_icc.c:419
#6  0x00007ffff7b1dfc7 in jas_iccprof_createfrombuf (buf=<optimised out>, len=<optimised out>) at src/libjasper/base/jas_icc.c:1796
#7  0x00007ffff7b45ca8 in jp2_decode (in=<optimised out>, optstr=0x0) at src/libjasper/jp2/jp2_dec.c:307
#8  0x00007ffff7b27919 in jas_image_decode (in=0x618650, fmt=3, optstr=0x0) at src/libjasper/base/jas_image.c:436
#9  0x0000000000401dd8 in main (argc=9, argv=<optimised out>) at src/appl/jasper.c:235

Regards,

Thuan
[jasper_crash_1.zip](https://github.com/jasper-software/jasper/files/6659604/jasper_crash_1.zip)

**Comment by mdadams** [comment]
The problem should now  fixed on the master branch.  The function in question should have returned with an error instead of aborting.
