### ISSUE TITLE
JasPer crashes due to jas_init()/jas_cleanup() when image was not actually read.  Also use of uninitialized data.

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#298]
Oss-fuzz found a problem if JasPer was initialized via a jas_init() 
[oss-fuzz-37535.tar.gz](https://github.com/jasper-software/jasper/files/7049942/oss-fuzz-37535.tar.gz)
but an image was never read.  Oss-fuzz complains about use of an uninitialized value but I get a 'jas_allocator' assertion in jas_cleanup() in my own testing.  It seems that there is more than one bug here.

        ==790==WARNING: MemorySanitizer: use-of-uninitialized-value
            #0 0x135d752 in jas_strtok jasper/src/libjasper/base/jas_string.c:108:6
            #1 0x13457e0 in jas_init_codecs jasper/src/libjasper/base/jas_init.c:386:16
            #2 0x1344c2d in jas_init_helper jasper/src/libjasper/base/jas_init.c:352:6
            #3 0x134492f in jas_init jasper/src/libjasper/base/jas_init.c:298:9
            #4 0xce34b0 in initialize_jasper graphicsmagick/coders/jp2.c:444:7
            #5 0xcd6fa4 in ReadJP2Image graphicsmagick/coders/jp2.c:521:3
            #6 0x6469c6 in ReadImage graphicsmagick/magick/constitute.c:1630:13
            #7 0x994175 in DCM_ReadNonNativeImages graphicsmagick/coders/dcm.c:7325:22
            #8 0x98d91a in ReadDCMImage graphicsmagick/coders/dcm.c:7529:14
            #9 0x6469c6 in ReadImage graphicsmagick/magick/constitute.c:1630:13
            #10 0x5d670c in BlobToImage graphicsmagick/magick/blob.c:764:13
            #11 0x5339c4 in Magick::Image::read(Magick::Blob const&) graphicsmagick/Magick++/lib/Image.cpp:1591:5
            #12 0x527592 in LLVMFuzzerTestOneInput graphicsmagick/fuzzing/coder_fuzzer.cc:22:15
            #13 0x45a833 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long)
            #14 0x446102 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:323:6
            #15 0x44bd0e in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long))
            #16 0x4754a2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
            #17 0x7efc21d3283f in __libc_start_main /build/glibc-e6zv40/glibc-2.23/csu/libc-start.c:291
            #18 0x4213a8 in _start
        
          Uninitialized value was created by an allocation of 'saveptr' in the stack frame of function 'jas_init_codecs'
            #0 0x1345540 in jas_init_codecs jasper/src/libjasper/base/jas_init.c:372
        
        SUMMARY: MemorySanitizer: use-of-uninitialized-value (/mnt/scratch0/clusterfuzz/bot/builds/clusterfuzz-builds_graphicsmagick_82a1c4b13860dcfd1688513621b8894ad0e8a5c8/revisions/coder_DCM_fuzzer+0x135d752)

**Comment by mdadams** [comment]
> Yesterday I switched development GraphicsMagick to use jas_initialize,
> but not yet using any of the optional features. This is to try to
> stem the bleeding and lessen the huge number of oss-fuzz reports
> related to JasPer.

For the time being, it would be a good idea not to use too many new
features, as I think that I still need to make some changes to the API
before things will be ready for a release, as addressing some of the
outstanding issues probably require some API changes.

**Comment by bobfriesenhahn** [comment]
On Sat, 28 Aug 2021, Michael Adams wrote:

>> Yesterday I switched development GraphicsMagick to use jas_initialize,
>> but not yet using any of the optional features. This is to try to
>> stem the bleeding and lessen the huge number of oss-fuzz reports
>> related to JasPer.
>
> For the time being, it would be a good idea not to use too many new
> features, as I think that I still need to make some changes to the API
> before things will be ready for a release, as addressing some of the
> outstanding issues probably require some API changes.

GraphicsMagick will use JasPer defaults for some time.  And 
particularly for a GraphicsMagick release if JasPer is not released 
yet.

Bob
-- 
Bob Friesenhahn
***@***.***, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by mdadams** [comment]
@bobfriesenhahn It is my understanding that the bug(s) that this issue (i.e., #298) was tracking was fixed by some of my other code changes.  In particular, it is my understanding that the following issue has been fixed: "JasPer crashes due to jas_init()/jas_cleanup() when image was not actually read. Also use of uninitialized data."  So, I am closing this issue.

**Comment by mdadams** [comment]
On Fri, 27 Aug 2021, Bob Friesenhahn wrote:
> The fact that jas_cleanup is registered as an atexit function is
> annoying but what makes it most problematic is that recently it added
> an assertion if it was called when cleanup has already been done
> rather than simply not doing anything.

I have tentatively decided to make a breaking change to the API for JasPer
to address this problem.  In particular, I have changed jas_init so that
it no longer registers jas_cleanup as an atexit handler.  This change
is in commit a21a00eb7fcf5a871ee83fa30589da1587b8afcf (on master).
Based on our recent discussions as well as things that others have
said in the past, I think that this solution is the lesser of many
evils.  The only problem that I can see this breaking change making is
introducing memory leaks into applications.  I think that this is better
than preventing some applications from being able to use JasPer altogether
on some platforms (due to an atexit handler doing bad things).

**Comment by bobfriesenhahn** [comment]
On Mon, 20 Sep 2021, Michael Adams wrote:
>
> I have tentatively decided to make a breaking change to the API for JasPer
> to address this problem.  In particular, I have changed jas_init so that
> it no longer registers jas_cleanup as an atexit handler.  This change
> is in commit a21a00eb7fcf5a871ee83fa30589da1587b8afcf (on master).
> Based on our recent discussions as well as things that others have
> said in the past, I think that this solution is the lesser of many
> evils.  The only problem that I can see this breaking change making is
> introducing memory leaks into applications.  I think that this is better
> than preventing some applications from being able to use JasPer altogether
> on some platforms (due to an atexit handler doing bad things).

That is good.  Applications using the new initialization function can 
also invoke jas_cleanup.  However, JasPer would need to make sure that 
it returns to the invoking application rather than doing something bad 
like just quitting.

Oss-fuzz has discovered a few more serious issues in JasPer (some of 
them likely new) that I will be looking at and trying to turn into a 
form of bug report which is acceptable to you.

Bob
-- 
Bob Friesenhahn
***@***.***, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by mdadams** [comment]
On Mon, 20 Sep 2021, Bob Friesenhahn wrote:
> That is good. Applications using the new initialization function can
> also invoke jas_cleanup. However, JasPer would need to make sure that
> it returns to the invoking application rather than doing something bad
> like just quitting.

Just to clarify, I am not planning to change the behavior of jas_cleanup.
That is, jas_cleanup just cleans up the library (e.g., frees internally
allocated resources like memory) but does not terminate the program,
if this was your concern.
