### ISSUE TITLE
jas_iccprof_createfrombuf assertion with JP2, custom allocator, and custom streams

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#307]
This is based on an oss-fuzz report.  I do not know how to reproduce this using the Jasper utility.

GraphicsMagick is using a custom memory allocator with development JasPer.  Oss-fuzz reports that this happens:

```
        warning: not enough tile data (1 bytes)
        coder_JP2_fuzzer: /src/jasper/src/libjasper/base/jas_stream.c:204: jas_stream_t *jas_stream_memopen(char *, size_t): Assertion `(buf && bufsize > 0) || (!buf)' failed.
        AddressSanitizer:DEADLYSIGNAL
        =================================================================
        ==10697==ERROR: AddressSanitizer: ABRT on unknown address 0x0539000029c9 (pc 0x7f5ea9e7118b bp 0x7f5ea9fe6588 sp 0x7ffe77bb2af0 T0)
            #0 0x7f5ea9e7118b in raise /build/glibc-eX1tMB/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:51:1
            #1 0x7f5ea9e50858 in abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:79:7
            #2 0x7f5ea9e50728 in __assert_fail_base /build/glibc-eX1tMB/glibc-2.31/assert/assert.c:92:3
            #3 0x7f5ea9e61f35 in __assert_fail /build/glibc-eX1tMB/glibc-2.31/assert/assert.c:101:3
            #4 0xda48e9 in jas_stream_memopen jasper/src/libjasper/base/jas_stream.c:204:2
            #5 0xd8b65f in jas_iccprof_createfrombuf jasper/src/libjasper/base/jas_icc.c:1759:13
            #6 0xdaef5b in jp2_decode jasper/src/libjasper/jp2/jp2_dec.c:315:13
            #7 0x985641 in ReadJP2Image graphicsmagick/coders/jp2.c:663:17
            #8 0x5b5c77 in ReadImage graphicsmagick/magick/constitute.c:1630:13
            #9 0x5635d9 in BlobToImage graphicsmagick/magick/blob.c:764:13
            #10 0x4eefc5 in Magick::Image::read(Magick::Blob const&) graphicsmagick/Magick++/lib/Image.cpp:1591:5
            #11 0x4da236 in LLVMFuzzerTestOneInput graphicsmagick/fuzzing/coder_fuzzer.cc:22:15
            #12 0x4db02b in main
            #13 0x7f5ea9e520b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
            #14 0x41f60d in _start
        
        AddressSanitizer can not provide additional info.
        SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x4618b)
        ==10697==ABORTING
```
Adding/removing ICC profiles has worked with previous JasPer versions.

The following is a sample file which causes the problem:

[clusterfuzz-testcase-minimized-coder_JP2_fuzzer-4842173204398080.fuzz.gz](https://github.com/jasper-software/jasper/files/7577045/clusterfuzz-testcase-minimized-coder_JP2_fuzzer-4842173204398080.fuzz.gz

**Comment by mdadams** [comment]
I cannot reproduce.  I get:

    imginfo < /tmp/mdadams/clusterfuzz-testcase-minimized-coder_JP2_fuzzer-4842173204398080.fuzz 
    tile too large
    error: cannot decode code stream
    jas_image_decode: decode operation failed
    cannot load image

The code does not crash.

**Comment by bobfriesenhahn** [comment]
I assume that the default JasPer build has asserts disabled, which is why I do not encounter them.  It appears that this crash is due to jp2_dec.c at around line 315 not assuring that the arguments supplied to jas_iccprof_createfrombuf() are not zero/null.  The assert in jas_stream_memopen() assumes that the arguments have already been validated.

**Comment by bobfriesenhahn** [comment]
Checking GraphicsMagick, I found that it does not know how to save ICC profiles via JasPer, but it does know how to retrieve them from JasPer.  But this crash is happening in the initial jp2_decode().

**Comment by bobfriesenhahn** [comment]
So I just tested (by hand) using GraphicsMagick and I get:

```
 ./utilities/gm convert -debug profile,coder jp2:/home/bfriesen/bugs/open/oss-fuzz-41091/clusterfuzz-testcase-minimized-coder_JP2_fuzzer-4842173204398080.fuzz info-
09:52:08 0:0.008648  0.000u 37536 constitute.c/ReadImage/1624/Coder:
  Invoking "JP2" decoder (JPEG-2000 JP2 File Format Syntax) subimage=0 subrange=0
09:52:08 0:0.008697  0.000u 37536 jp2.c/initialize_jasper/437/Coder:
  Initializing JasPer...
09:52:08 0:0.008879  0.000u 37536 jp2.c/ReadJP2Image/565/Coder:
  Requested format is "JP2"
09:52:08 0:0.008902  0.000u 37536 jp2.c/ReadJP2Image/651/Coder:
  JP2 options = "max_samples=41913679872"
09:52:08 0:0.008910  0.000u 37536 jp2.c/ReadJP2Image/661/Coder:
  Decoding JP2...
warning: not enough tile data (1 bytes)
gm: /home/bfriesen/src/jasper.git/src/libjasper/base/jas_stream.c:204: jas_stream_memopen: Assertion `(buf && bufsize > 0) || (!buf)' failed.
./utilities/gm convert: abort due to signal 6 (SIGABRT) "Abort"...
zsh: abort (core dumped)  ./utilities/gm convert -debug profile,coder  info-
```

**Comment by mdadams** [comment]
Assuming your analysis is correct, the only potential issue I can see is that the code will die if it is asked to read ICC proile data of length 0.  This must be the bug.  I was finally able to reproduce the problem with:

    imginfo --max-samples 100000000 < /tmp/mdadams/clusterfuzz-testcase-minimized-coder_JP2_fuzzer-4842173204398080.fuzz

The problem is now gone with my fix.  I will push the changes momentarily.  They are not on master yet.
