### ISSUE TITLE
Assertion `mb->magic == JAS_BMA_MAGIC' failed.

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#308]
Using development JasPer from GraphicsMagick and a custom memory allocator, oss-fuzz is detecting this issue:

```
        coder_JPC_fuzzer: /src/jasper/src/libjasper/base/jas_malloc.c:317: jas_mb_t *jas_get_mb(void *): Assertion `mb->magic == JAS_BMA_MAGIC' failed.
        AddressSanitizer:DEADLYSIGNAL
        =================================================================
        ==9553==ERROR: AddressSanitizer: ABRT on unknown address 0x053900002551 (pc 0x7ff7a60bc18b bp 0x7ff7a6231588 sp 0x7fff6d7f47e0 T0)
            #0 0x7ff7a60bc18b in raise /build/glibc-eX1tMB/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:51:1
            #1 0x7ff7a609b858 in abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:79:7
            #2 0x7ff7a609b728 in __assert_fail_base /build/glibc-eX1tMB/glibc-2.31/assert/assert.c:92:3
            #3 0x7ff7a60acf35 in __assert_fail /build/glibc-eX1tMB/glibc-2.31/assert/assert.c:101:3
            #4 0xfcb70e in jas_get_mb jasper/src/libjasper/base/jas_malloc.c:317:2
            #5 0xfca6be in jas_basic_free jasper/src/libjasper/base/jas_malloc.c:566:8
            #6 0xfc8acd in jas_free jasper/src/libjasper/base/jas_malloc.c:163:2
            #7 0xfd7776 in mem_close jasper/src/libjasper/base/jas_stream.c:1349:3
            #8 0xfd0f3b in jas_stream_close jasper/src/libjasper/base/jas_stream.c:592:2
            #9 0xfdfd1b in jpc_getms jasper/src/libjasper/jpc/jpc_cs.c:277:4
            #10 0xfeb240 in jpc_dec_decode jasper/src/libjasper/jpc/jpc_dec.c:418:14
            #11 0xfea43c in jpc_decode jasper/src/libjasper/jpc/jpc_dec.c:270:6
            #12 0xb1f727 in ReadJP2Image graphicsmagick/coders/jp2.c:673:17
            #13 0x5cccf1 in ReadImage graphicsmagick/magick/constitute.c:1630:13
            #14 0x55393c in BlobToImage graphicsmagick/magick/blob.c:764:13
            #15 0x4e57ac in Magick::Image::read(Magick::Blob const&) graphicsmagick/Magick++/lib/Image.cpp:1591:5
            #16 0x4db188 in LLVMFuzzerTestOneInput graphicsmagick/fuzzing/coder_fuzzer.cc:22:15
            #17 0x4dd185 in ExecuteFilesOnyByOne aflplusplus/utils/aflpp_driver/aflpp_driver.c:191:7
            #18 0x4dcff5 in main aflplusplus/utils/aflpp_driver/aflpp_driver.c:0
            #19 0x7ff7a609d0b2 in __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/libc-start.c:308:16
            #20 0x42098d in _start
        
        AddressSanitizer can not provide additional info.
        SUMMARY: AddressSanitizer: ABRT (/lib/x86_64-linux-gnu/libc.so.6+0x4618b)
        ==9553==ABORTING
```

I am not sure of the cause but it may be due to using a custom memory allocator
.  Is it possible that support for a custom memory allocator is not yet uniformly implemented in JasPer?

The following is the test file used:

[clusterfuzz-testcase-minimized-coder_JPC_fuzzer-6102321038229504.gz](https://github.com/jasper-software/jasper/files/7577058/clusterfuzz-testcase-minimized-coder_JPC_fuzzer-6102321038229504.gz)

**Comment by mdadams** [comment]
This works without a crash on my development machine.
I am using:
    imginfo < clusterfuzz-testcase-minimized-coder_JPC_fuzzer-6102321038229504
The output I get is:
==========
cannot get marker segment
jas_image_decode: decode operation failed
cannot load image
==========
So, I think that you may be doing something wrong with your use of custom allocators.  Please note that you cannot interchange the pointers obtained by your allocator and jas_malloc.  For example, the following will fail spectacularly:
void *p = my_custom_malloc_like_function(some_size);
jas_free(p);  /* BOOM! */
This will also crash and burn:
void *p = jas_malloc(some_size);
my_custom_free_like_function(p); /* BAD THINGS HAPPEN! */
By chance, are you doing something like this?

**Comment by mdadams** [comment]
BTW, the failed assertion is saying the code is trying to access a  jasper memory block that is not a jasper memory block, where "jasper memory block" means a block allocated by jas_malloc.

**Comment by bobfriesenhahn** [comment]
On Tue, 23 Nov 2021, Michael Adams wrote:
> So, I think that you may be doing something wrong with your use of custom allocators.  Please note that you cannot interchange the pointers obtained by your allocator and jas_malloc.  For example, the following will fail spectacularly:
> void *p = my_custom_malloc_like_function(some_size);
> jas_free(p);  /* BOOM! */
> This will also crash and burn:
> void *p = jas_malloc(some_size);
> my_custom_free_like_function(p); /* BAD THINGS HAPPEN! */
> By chance, are you doing something like this?

As far as I can tell, no.  In fact, in my own testing (with valgrind) 
I am not able to reproduce the issues that oss-fuzz does.  Oss-fuzz 
seems to use the latest git sources for everything (possibly including 
the system C library) and builds everything consistently for 
asan/ubsan whereas I only use asan/ubsan for GraphicsMagick itself. 
As a result I turn to using valgrind for some testing.

I recall seeing a case where it seemed that JasPer was making 
decisions based on uninitialized data but I don't recall where it was 
or how to reproduce.

Bob
-- 
Bob Friesenhahn
***@***.***, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by mdadams** [comment]
There was a memory initialization bug that was fixed some time ago.  I don't know if that is the one that you are thinking of. In any case, if you are able to recall exactly what code problem you saw, please let me know, since I am still not having any success reproducing this problem.  Even valgrind --tool=memcheck is not finding anything.

A long time ago, I think that you had said something to the effect that GraphicsMagick bypasses JasPer interfaces to create some kind of custom jas_stream_t.  If the memory for these streams are allocated using your custom allocator, this will not work.  It is critical that only jas_malloc be used to allocate memory used for streams or anything else in JasPer.

BTW, sorry about my bizarre formatting with a huge bold font in one of my earlier posts for this issue.  I don't know what happened there.  I fixed it so it doesn't look like my post is screaming anymore.

**Comment by bobfriesenhahn** [comment]
On Mon, 29 Nov 2021, Michael Adams wrote:

> There was a memory initialization bug that was fixed some time ago. 
> I don't know if that is the one that you are thinking of. In any 
> case, if you are able to recall exactly what code problem you saw, 
> please let me know, since I am still not having any success 
> reproducing this problem.  Even valgrind --tool=memcheck is not 
> finding anything.

I will study this issue some more to try to understand how to 
reproduce it (if possible).

> A long time ago, I think that you had said something to the effect 
> that GraphicsMagick bypasses JasPer interfaces to create some kind 
> of custom jas_stream_t.  If the memory for these streams are 
> allocated using your custom allocator, this will not work.  It is 
> critical that only jas_malloc be used to allocate memory used for 
> streams or anything else in JasPer.

After GraphicsMagick has registered its custom memory allocators using 
the new 3.0 API, it only uses jas_malloc.

> BTW, sorry about my bizarre formatting with a huge bold font in one 
> of my earlier posts for this issue.  I don't know what happened 
> there.  I fixed it so it doesn't look like my post is screaming 
> anymore.

I am reading this without unusual fonts so no problem.

Bob
-- 
Bob Friesenhahn
***@***.***, http://www.simplesystems.org/users/bfriesen/
GraphicsMagick Maintainer,    http://www.GraphicsMagick.org/
Public Key,     http://www.simplesystems.org/users/bfriesen/public-key.txt

**Comment by mdadams** [comment]
I do not see this problem showing up anymore in the current list at:
    https://bugs.chromium.org/p/oss-fuzz/issues/list?q=graphicsmagick
So, I am going to assume that either that this issue was either a false positive or was fixed by other changes made since the time that the error was flagged.  Consequently, I'm going to close this issue.
