### ISSUE TITLE
Cannot use in C++: reserved word 'class'

### ISSUE THREAD

**Issue by egorpugin** [jasper-software/jasper#318]
https://github.com/jasper-software/jasper/blob/master/src/libjasper/include/jasper/jas_log.h#L122

**Comment by mdadams** [comment]
> https://github.com/jasper-software/jasper/blob/master/src/libjasper/include/jasper/jas_log.h#L122

In addition to fixing the problem, I added a simple C++ test program to catch incompatibilities with C++ like this in the future.  Hopefully, something like this will never make it into a release again.
