### ISSUE TITLE
jas_safeui64_div has a bug

### ISSUE THREAD

**Issue by geraldgg** [jasper-software/jasper#323]
Around ligne 472 in jas_math.h

		result.value = x.value / y.valid;

I guess it should be 
		result.value = x.value / y.value;

**Comment by jubalh** [comment]
https://github.com/jasper-software/jasper/blob/5e45df490870073c9f38785724959c1a429e95a0/src/libjasper/include/jasper/jas_math.h#L472

introduced with https://github.com/jasper-software/jasper/commit/def49688. So JasPer versions affected are: 3.0.0 until 3.0.3.

**Comment by mdadams** [comment]
@jubalh Thanks for the PR.

@geraldgg Michael Vetter's PR has been merged to fix this problem. Fortunately, this buggy function is not called in the current code base.  So, it has no security or other impact.  At least it is now fixed for the day when it is actually called.

**Comment by geraldgg** [comment]
I just saw a warning that catched my eye. Good to know that it wasn't used, and is now fixed, thanks for prompt response.
