### ISSUE TITLE
Replace all calls to `abort` function with a proper error handling

### ISSUE THREAD

**Issue by theta682** [jasper-software/jasper#326]
The library should not kill the application by calling `abort()` each time something unpredicted happens. It should report an issue to the calling application instead.

**Comment by theta682** [comment]
@mdadams there are some more `abort()` in the code besides of #325.

**Comment by mdadams** [comment]
@theta682 I have dealt with this issue as described in my comment for PR #325.  So, I am closing this issue.  If you still have any concerns, please let me know.

**Comment by theta682** [comment]
I think one place still has to be refactored: https://github.com/jasper-software/jasper/blob/6a5d65aef9c80e6accbfa52e70f89fb29bc89838/src/libjasper/base/jas_cm.c#L1421
This can cause similar issue to #325.

**Comment by theta682** [comment]
Thanks for new release

**Comment by mdadams** [comment]
> I think one place still has to be refactored:
> 
> https://github.com/jasper-software/jasper/blob/6a5d65aef9c80e6accbfa52e70f89fb29bc89838/src/libjasper/base/jas_cm.c#L1421
> 
> This can cause similar issue to #325.

The function jas_clrspc_numchans  is making a legitimate use of abort.  It is a precondition of the jas_clrspc_numchans function that the color space family passed to the function be a valid one, and the only valid values are: JAS_CLRSPC_FAM_XYZ, JAS_CLRSPC_FAM_LAB, JAS_CLRSPC_FAM_GRAY, JAS_CLRSPC_FAM_RGB, and JAS_CLRSPC_FAM_YCBCR.  If this function would hit the default clause of the switch (where the abort call is located), this would mean that the caller has gone insane and is violating preconditions of other functions including jas_clrspc_numchans.  Therefore, this is a fatal programming error and the program should be terminated.  If this abort call is hit there is a serious bug in the caller where the caller has not checked for valid color profile information.  In such a case, the code that would need to be fixed is somewhere in the caller, not the code in jas_clrspc_numchans.  I hope that makes sense.

**Comment by theta682** [comment]
Thank you for your explanation. I'm not fully convinced to use `abort()`. However, if the client code uses incorrect values it is OK to do this. It is important not to crash the application validating the values from the file. It is a normal situation when the file is broken.

**Comment by mdadams** [comment]
If there are any specific cases where abort is used that you are concerned about, please identify them.  As I said before, I could have overlooked something when reviewing the code, but I did not see any inappropriate uses of abort.  If the library user violates the JasPer library API, it is not unreasonable to call abort.
