### ISSUE TITLE
[Minor issue] jasper-3.0.6.tar.gz does not extract towards jasper-3.0.6

### ISSUE THREAD

**Issue by rubyFeedback** [jasper-software/jasper#331]
[Minor issue] jasper-3.0.6.tar.gz does not extract towards jasper-3.0.6

URL used was:

https://github.com/jasper-software/jasper/releases/download/version-3.0.6/jasper-3.0.6.tar.gz

It's not a big deal, I re-package anyway, but it was initially surprising. I think having a consistent
"archive-name.tar.xz == archive-name" when extracted would be simpler. I believe older
jasper releases follow that pattern, only 3.6.0 behaves oddly.

**Comment by mdadams** [comment]
I don't understand.  The archive for jasper-3.0.6.tar.gz does place everything in the directory jasper-3.0.6.   Things work fine for me with the archive at the link that you provided.
