### ISSUE TITLE
Undefined Behavior: some runtime errors

### ISSUE THREAD

**Issue by xiaoxiaoafeifei** [jasper-software/jasper#334]
Hi,
I found some runtime errors on Version 3.0.6

Here's UBSAN log:
test@9e5cd2886520:~/fuzz_target/jasper-3.0.6/builder$ /usr/local/bin/jasper --input input_file --output /dev/null --output-format jp2
/home/zll/fuzz_target/jasper-3.0.6/src/libjasper/pgx/pgx_dec.c:512:10: runtime error: shift exponent 32 is too large for 32-bit type 'int'
SUMMARY: AddressSanitizer: undefined-behavior /home/zll/fuzz_target/jasper-3.0.6/src/libjasper/pgx/pgx_dec.c:512:10 in 
/home/zll/fuzz_target/jasper-3.0.6/src/libjasper/pgx/pgx_dec.c:513:25: runtime error: left shift of 1 by 31 places cannot be represented in type 'int'
SUMMARY: AddressSanitizer: undefined-behavior /home/zll/fuzz_target/jasper-3.0.6/src/libjasper/pgx/pgx_dec.c:513:25 in 
/home/zll/fuzz_target/jasper-3.0.6/src/libjasper/base/jas_image.c:1011:59: runtime error: shift exponent 32 is too large for 32-bit type 'int'
SUMMARY: AddressSanitizer: undefined-behavior /home/zll/fuzz_target/jasper-3.0.6/src/libjasper/base/jas_image.c:1011:59 in

/home/zll/fuzz_target/jasper-3.0.6/src/libjasper/base/jas_image.c:1011:59: runtime error: shift exponent 32 is too large for 32-bit type 'int'
SUMMARY: AddressSanitizer: undefined-behavior /home/zll/fuzz_target/jasper-3.0.6/src/libjasper/base/jas_image.c:1011:59 in 
/home/zll/fuzz_target/jasper-3.0.6/src/libjasper/base/jas_image.c:1011:38: runtime error: shift exponent 32 is too large for 32-bit type 'int'
SUMMARY: AddressSanitizer: undefined-behavior /home/zll/fuzz_target/jasper-3.0.6/src/libjasper/base/jas_image.c:1011:38 in 

/home/zll/fuzz_target/jasper-3.0.6/src/libjasper/base/jas_image.c:672:7: runtime error: left shift of 53689972015759360 by 8 places cannot be represented in type 'jas_seqent_t' (aka 'long')
SUMMARY: AddressSanitizer: undefined-behavior /home/zll/fuzz_target/jasper-3.0.6/src/libjasper/base/jas_image.c:672:7 in

Steps to Reproduce:
1. CC=clang /usr/local/bin/cmake -DCMAKE_C_FLAGS="-fsanitize=undefined,address,leak" -B builder
2. make & make install
3. /usr/local/bin/jasper --input input_file --output /dev/null --output-format jp2

[input.zip](https://github.com/jasper-software/jasper/files/9230432/input.zip)

**Comment by mdadams** [comment]
I cannot reproduce this problem on the master branch.
I get the following:

jasper --input input --output /dev/null -T jp2
cannot get precision
cannot get header
jas_image_decode: decode operation failed
error: cannot load image data

That is, the program fails with an error, as it should.  Unless you can provide a reproducer for the most recent commit on the master branch, I will assume that this problem has been fixed by other changes made since 3.0.6.
