### ISSUE TITLE
Provides problem on RockyLinux 8

### ISSUE THREAD

**Issue by thebaptiste** [jasper-software/jasper#340]
Hello

I am using jasper-libs on RockyLinux 8.5 (64 bits)
For some reason I would like to install jasper-libs by referencing the libjasper.so.4 library doing : 
`yum install 'libjasper.so.4()(64bit)'`

This kind of installation works for many packages

But it doesn't work for jasper-libs : 
`No match for argument: libjasper.so.4()(64bit)`

Yet jasper-libs provides  libjasper.so.4()(64bit) : 
```
yum install jasper-libs
(...)
Installed:
  jasper-libs-2.0.28-3.el9.x86_64

rpm -q --provides jasper-libs
jasper-libs = 2.0.28-3.el9
jasper-libs(x86-64) = 2.0.28-3.el9
libjasper.so.4()(64bit)
```
I don't understand why it doesn't work, it should...

May be it's not your problem but a packaging problem in RockyLinux...

Regards

**Comment by jubalh** [comment]
> May be it's not your problem but a packaging problem in RockyLinux...

I'm not sure whether it is a packaging problem but for sure it's a problem that you need to ask your distribution.

I don't know either yum nor the details of RedHat/RockyLinux packaging. So I have no idea how yum works or is supposed to work in this case.
