### ISSUE TITLE
[Help document bug] For imginfo, the help document misses some options

### ISSUE THREAD

**Issue by ccccmd** [jasper-software/jasper#343]
The "--help" option of imginfo misses the option "X", "default-memory-limit", "list-enabled-formats“，"list-all-formats", "enable-format" and "enable-all-formats" for version 3.0.6.

+ For the option "X", the following code appears during option parsing and modifies the special in src/app/imginfo.c:207-208 for version 3.0.6.

```
			special = 1;
			break;
```

+ For the option "default-memory-limit", the following code appears during option parsing and modifies the default_mem_limit in src/app/imginfo.c:210-211 for version 3.0.6.

```
			default_mem_limit = true;
			break;
```

+ For the option "list-enabled-formats", the following code appears during option parsing and modifies the list_codecs and list_codecs_all in src/app/imginfo.c:217-219 for version 3.0.6.

```
			list_codecs = 1;
			list_codecs_all = 0;
			break;
```

+ For the option "list-all-formats", the following code appears during option parsing and modifies the list_codecs and list_codecs_all in src/app/imginfo.c:213-215 for version 3.0.6.

```
			list_codecs = 1;
			list_codecs_all = 1;
			break;
```

+ For the option "enable-format", the following code appears during option parsing and modifies the enable_format in src/app/imginfo.c:221-222 for version 3.0.6.

```
			enable_format = jas_optarg;
			break;
```

+ For the option "enable-all-formats", the following code appears during option parsing and modifies the enable_all_formats in src/app/imginfo.c:224-225 for version 3.0.6.

```
			enable_all_formats = 1;
			break;
```

But they do not appear in the document provided by "--help".

It may prevent users from using the relevant function.

**Comment by mdadams** [comment]
See the comment for #344.  This issue has been fixed on the master branch.  See commit e97639fe47faed62703ba47c1071b91e3d76eb41.
