### ISSUE TITLE
Improve pkg-config file generation

### ISSUE THREAD

**Issue by kmilos** [jasper-software/jasper#349]
It would be good to improve the CMake generated .pc file for relocatability - namely, it should use [${prefix} etc. variables and relative paths whenever possible](https://people.freedesktop.org/~dbn/pkg-config-guide.html), but still support absolute paths when so required.

See e.g. [libjxl](https://github.com/libjxl/libjxl/blob/3f6ec60ce6890132c1e2ea9719de5981042a1d96/lib/jxl.cmake#L642-L663) and [libtiff](https://gitlab.com/libtiff/libtiff/-/blob/31d9e9f73dc8b6fa599c931d9ff058d8ea32795c/cmake/PkgConfig.cmake#L48-63)

**Comment by jubalh** [comment]
I didn't check right now. But I thought that we already support a prefix when installing.
If not, can you open an PR?

**Comment by jubalh** [comment]
@kmilos ping

**Comment by jubalh** [comment]
Unfortunately I'm also no expert. But to me the PR looks ok. I patched the openSUSE package to use this PR and everything was build/installed correctly at to the usual locations. The tooling didn't point to any problems either. So I would say let's take it.

**Comment by mdadams** [comment]
@jubalh Thanks for your feedback.  Since you don't have any concerns and I don't see anything obviously wrong with the PR, I have merged it.
