### ISSUE TITLE
CMake: Avoid conditional lib names based on generators

### ISSUE THREAD

**Issue by SpaceIm** [jasper-software/jasper#350]
Generators are an internal detail of users, lib name shouldn't depend on it. Currently a `d` postifx is added to debug lib name in case of multi config generator. It makes lib name & packaging content unpredictable for conan package manager for a given tuple of compiler/os/arch/build type.

**Comment by SpaceIm** [comment]
To remove this block: https://github.com/jasper-software/jasper/blob/402d096b39f4f618ad9e6ff2b4fc1b5eb260a2e4/CMakeLists.txt#L266-L268

**Comment by jubalh** [comment]
@theta682 you added this in https://github.com/jasper-software/jasper/commit/0f020fd7.
Unfortunately your commit message is quite unhelpful.

But I see that in https://github.com/jasper-software/jasper/pull/301 you actually wrote:

```
    Make CMake code style similar to standard CMake
    Improve multi-configuration support: Add "d" suffix for Debug configuration
    Improve detection of snprintf on Windows
    Use BUILD_SHARED_LIBS to declare JAS_ENABLE_SHARED if it is defined
    Reduce warning about GLUT on Windows
```

Please do one change per commit in the future and describe it.

Anyways, the PR mentions `Improve multi-configuration support: Add "d" suffix for Debug configuration`. @theta682 what do you think about @SpaceIm suggestion here?

**Comment by theta682** [comment]
In the case of "multi-configuration" debug suffix is required. CPack which uses CMake install will replace all configurations with the last one. There is no way to package both configurations at once. For preparing a separate debug package it is better to use nonmulti-configuration. I am strongly against removing the debug suffix when multi-configuration is used.

**Comment by mdadams** [comment]
@jubalh: Based on the comments from @theta682, I would be inclined to leave JasPer unchanged in the above regard.  Should I close this issue?

**Comment by SpaceIm** [comment]
This makes things harder for package managers (we would have to patch forever in conan just because a user has an a very specific and unusual usage of the build system of library :s ).
I never seen such weird name logic in any CMake based project. Debug suffix based on compiler, yes (but honestly it's a pain), but it doesn't make sense when it depends on generator.

**Comment by theta682** [comment]
@SpaceIm if you package using multi-configuration you must support multiple files. Don't use multi-configuration generator.

**Comment by theta682** [comment]
After more thought, I can agree with @SpaceIm that `CMAKE_DEBUG_POSTFIX` can be provided externally. See #351.

**Comment by jubalh** [comment]
Thanks @theta682 for the patch and @SpaceIm for the discussion.

**Comment by mdadams** [comment]
Thank you all @theta682 @SpaceIm @jubalh
