### ISSUE TITLE
Warning during compilation

### ISSUE THREAD

**Issue by franz-xaver** [jasper-software/jasper#361]
Building Custom Rule C:/builds/pco/entwicklung/team-software/3rd-party-libraries/jasper/jasper-version-4.0.0/src/libjasper/CMakeLists.txt
  jas_cm.c
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: macro expansion producing 'defined' has undefined behavior [C:\builds\pco\entwicklung\team-software\3rd-party-libraries\jasper\jasper-version-4.0.0\windows_x64\src\libjasper\libjasper.vcxproj]

Anyone else here getting the same warning?

Regards,
Franz

**Comment by jubalh** [comment]
Which warning?
Your log is super hard to read and weird formatted. It's hard to understand which line starts where.

To me it looks like:
`C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\um\winbase.h(9531,5): warning C5105: macro expansion producing 'defined' has undefined behavior` is not related to jasper at all.

**Comment by jubalh** [comment]
Also you can see that CI shows that JasPer master builds fine for various macos, windows and ubuntu version.
The last stable release builds fine for all kinds of Linux distros: https://repology.org/project/jasper/versions

**Comment by uvic-frodo** [comment]
I concur with jubalh's assessment.  This looks like a warning caused by whatever Microsoft is doing in their own winbase.h and possibly other headers.  This does not really look like a JasPer bug.

**Comment by franz-xaver** [comment]
Yep, that's the case. Using most recent windows SDK the error is gone.
