### ISSUE TITLE
oss-fuzz issue 60893: graphicsmagick:coder_JP2_fuzzer: Timeout in coder_JP2_fuzzer

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#378]
Please see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60893&sort=reported%20-id&q=graphicsmagick&can=6 for an GraphicsMagick oss-fuzz issue in JasPer which was first detected on  Jul 27, 2023, and is now open for public consumption.

**Comment by mdadams** [comment]
This does not hang with JasPer on the master branch.  It is somewhat slow to process on my machine.  It takes about 30 seconds or so before it exits saying the file is invalid.  So, this is not a bug.
