### ISSUE TITLE
graphicsmagick:coder_JPC_fuzzer: Floating-point-exception in jpc_pi_next

### ISSUE THREAD

**Issue by bobfriesenhahn** [jasper-software/jasper#382]
As part of the GraphicsMagick oss-fuzz testing, oss-fuzz discovered a floating-point-exception in Jasper's jpc_pi_next.  The issue is available to view at https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65625.  Since the issue has now exceeded the disclosure deadline, anyone should be able to view this issue and download the test case which triggers it.

**Comment by mdadams** [comment]
I cannot reproduce this problem.  When I decode the JPC file, I get this:

```
imginfo < 382.jpc 
warning: trailing garbage in marker segment (24 bytes)
warning: ignoring unknown marker segment (0xff20)
alignment failed
jpc_dec_decodepkt failed
jpc_dec_decodepkts failed
jas_image_decode: decode operation failed
cannot load image
```

This is the expected behavior.  In the absence of further information, I will have to assume that this bug is being observed in an older release of JasPer and the problem has subsequently been fixed.
