### ISSUE TITLE
Correct higher resolution level 9/7 energy weight approximations

### ISSUE THREAD

**Issue by boxerab** [jasper-software/jasper#385]
It's nice to see this project getting the attention it deserves.

I notice that the higher level 9/7 energy weights / L2 norms [are currently approximations](https://github.com/jasper-software/jasper/blob/master/src/libjasper/jpc/jpc_qmfb.c),
and that exact values can be found in the OpenJPH project [here](https://github.com/aous72/OpenJPH/blob/master/src/core/codestream/ojph_params.cpp).

With permission from @aous72, these approximations could be corrected.

Ideally, these values could be calculated through some script

Thanks!

**Comment by mdadams** [comment]
I would have to compute the correct values myself to be sure that they are correct.  I do not have any script handy to compute these values, however.
