### ISSUE TITLE
Not able to install on Raspberry PY OS

### ISSUE THREAD

**Issue by diegoriera** [jasper-software/jasper#389]
When I follow install instructions the error is returned.

CMake Error at build/cmake/modules/InSourceBuild.cmake:27 (message):
  The use of an in-source build has been detected (i.e., the binary directory
  specified to CMake is located in or under the source directory).  This can
  potentially trash the source tree.  In fact, if you are seeing this
  message, you may have already partially trashed the source tree.  The use
  of an in-source build is not officially supported and is therefore
  disallowed by default.  If you like to live dangerously and would like to
  override this default behavior, this can be accomplished via the CMake
  option ALLOW_IN_SOURCE_BUILD.

**Comment by mdadams** [comment]
This is not a JasPer bug.  It is considered a very bad practice to use in-source builds with CMake.  For this reason, JasPer does not support in-source builds.  The solution to your problem is simply not to use an in-source build.  Choose a different binary directory for CMake.
